Album.create(name: "Sgt. Pepper's Lonely Hearts Club Band", released_year: 1967)
Album.create(name: "Pet Sounds", released_year: 1966)
Album.create(name: "Revolver", released_year: 1966)
Album.create(name: "Highway 61 Revisited", released_year: 1965)
Album.create(name: "Rubber Soul", released_year: 1965)
Album.create(name: "What's Going On", released_year: 1971)
Album.create(name: "Exile on Main St.", released_year: 1972)
Album.create(name: "London Calling", released_year: 1979)
Album.create(name: "Blonde on Blonde", released_year: 1966)
Album.create(name: "The Beatles", released_year: 1968)